### ISSUE TITLE
Does not build with cmake

### ISSUE THREAD

**Issue by mquinson** [mcminickpt/mcmini#86]
Hello friends,

I just tried to build McMini from source, and it failed as follows. I will use the configure script (which works properly), but maybe you want to either fix or remove the cmake files?

Thanks,
Mt

```
$ cmake . && make
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pre-commit program...
-- Could not find pre-commit program
-- Initializing git submodules
-- Ignoring conditional subdirectory "tests": Tests only built with BUILD_TESTS=1
-- Configuring done (1.9s)
CMake Error at src/CMakeLists.txt:93 (add_executable):
  Cannot find source file:

    MCState.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:93 (add_executable):
  No SOURCES given to target: mcmini_demo


CMake Error at src/CMakeLists.txt:102 (add_library):
  No SOURCES given to target: mcmini_checker


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by maxwellpirtle** [comment]
Hey @mquinson, we're working on changing the architecture somewhat to help clearly delineate the component boundaries in the checker. The project structure will change somewhat significantly (for the better). If you're curious about the developments, look at the `design-improvements` branch and #87. That PR is going to be split into several smaller ones for better granularity. Feel free to participate once they're available (which should be shortly)

**Comment by mquinson** [comment]
Hey @maxwellpirtle, I'm glad you guys move forward, but I won't have the time to check on these dev unfortunately... I'm already struggling following what's happening in simgrid ;)
